# Generated by Django 5.0.4 on 2024-05-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='questions',
            field=models.TextField(unique=True),
        ),
    ]
